source "https://rubygems.org"

gem "iridium", github: 'radiumsoftware/iridium'
gem 'iridium-ember', github: 'radiumsoftware/iridium-ember'
gem "hydrogen", github: 'radiumsoftware/hydrogen'
gem "rake-pipeline", github: 'livingsocial/rake-pipeline'
